"""Turn a finished run into something usable outside Ustad.

The merge happens **on the CPU in fp16**, deliberately. During training the base weights
are NF4-quantised; merging a LoRA delta into 4-bit weights means quantising the result
again and losing most of what was learned. So the base model is reloaded unquantised, the
adapter is applied to those weights, and the merged result is written out in fp16.

Output is a directory containing the merged model, a copy of the adapter, a ready-to-use
``Modelfile``, and the exact commands for GGUF conversion.
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path
from typing import Any

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

from . import config
from . import dataset as store
from . import distill
from .events import bus

MODELFILE_TEMPLATE = """# Generated by Ustad for {name}
# Ollama imports Hugging Face safetensors directly for llama/qwen2/qwen3/gemma/mistral
# architectures, so this points straight at the merged directory.
FROM ./merged

PARAMETER temperature 0.7
PARAMETER top_p 0.9
"""

README_TEMPLATE = """# {name}

Distilled from **{teacher}** into **{student}** by Ustad.

| | |
|---|---|
| run | `{run_id}` |
| dataset | `{dataset}` ({pairs} pairs) |
| trainable params | {trainable:,} ({trainable_pct}% of the model) |
| steps | {steps} |
| loss | {first_loss} → {final_loss} |
| eval loss | {eval_loss} |

## Contents

```
merged/      fp16 merged model + tokenizer (load with transformers, or import into Ollama)
adapter/     the LoRA adapter on its own — small, and stackable on the base model
Modelfile    ready for `ollama create`
```

## Use it with Ollama

```bash
cd "{export_dir}"
ollama create {slug} -f Modelfile
ollama run {slug}
```

## Use it with transformers

```python
from transformers import AutoModelForCausalLM, AutoTokenizer

path = r"{merged_dir}"
tok = AutoTokenizer.from_pretrained(path)
model = AutoModelForCausalLM.from_pretrained(path, dtype="float16", device_map="auto")
ids = tok.apply_chat_template([{{"role": "user", "content": "your prompt"}}],
                              add_generation_prompt=True, return_tensors="pt").to(model.device)
print(tok.decode(model.generate(ids, max_new_tokens=256)[0][ids.shape[-1]:]))
```

## Convert to GGUF (optional, for a smaller quantised file)

Needs a llama.cpp checkout — a one-time clone, then everything stays local:

```bash
git clone https://github.com/ggml-org/llama.cpp
pip install -r llama.cpp/requirements.txt
python llama.cpp/convert_hf_to_gguf.py "{merged_dir}" --outfile "{slug}-f16.gguf" --outtype f16
llama.cpp/build/bin/llama-quantize "{slug}-f16.gguf" "{slug}-q4_k_m.gguf" Q4_K_M
```

Then point a Modelfile at the quantised file instead:

```
FROM ./{slug}-q4_k_m.gguf
```

## Keep the adapter separate instead

The adapter is a few megabytes and leaves the base model untouched:

```python
from peft import PeftModel
model = PeftModel.from_pretrained(base_model, r"{adapter_dir}")
```
"""


def export_dir(name: str) -> Path:
    return config.EXPORTS_DIR / store.safe_name(name)


def list_exports() -> list[dict[str, Any]]:
    exports = []
    for directory in sorted(config.EXPORTS_DIR.iterdir(), reverse=True) if config.EXPORTS_DIR.exists() else []:
        if not directory.is_dir():
            continue
        entry: dict[str, Any] = {"name": directory.name, "path": str(directory)}
        meta = directory / "export.json"
        if meta.exists():
            try:
                entry.update(json.loads(meta.read_text(encoding="utf-8")))
            except json.JSONDecodeError:
                pass
        entry["size_bytes"] = _dir_size(directory)
        exports.append(entry)
    return exports


def _dir_size(directory: Path) -> int:
    return sum(p.stat().st_size for p in directory.rglob("*") if p.is_file())


def export_run(run_id: str, name: str = "", merge: bool = True) -> dict[str, Any]:
    """Merge (optionally) and package a run. Blocking; run it in a worker thread."""
    run = distill.read_run(run_id)
    meta = run["meta"]
    adapter_src = config.RUNS_DIR / run["run_id"] / "adapter"
    if not (adapter_src / "adapter_config.json").exists():
        raise FileNotFoundError(f"No adapter found for run '{run_id}'. Train it first.")

    student = meta.get("student") or config.DEFAULT_STUDENT
    target = export_dir(name or run["run_id"])
    target.mkdir(parents=True, exist_ok=True)

    bus.publish("export.start", run_id=run["run_id"], name=target.name, merge=merge, path=str(target))

    adapter_dst = target / "adapter"
    if adapter_dst.exists():
        shutil.rmtree(adapter_dst)
    shutil.copytree(adapter_src, adapter_dst)
    bus.publish("export.progress", step="adapter copied", path=str(adapter_dst))

    merged_dir = target / "merged"
    if merge:
        bus.publish("export.progress", step=f"loading {student} on CPU in fp16")
        merged_dir = _merge(student, adapter_src, merged_dir)
        bus.publish("export.progress", step="merged model written", path=str(merged_dir))

    slug = target.name.lower().replace("_", "-")
    (target / "Modelfile").write_text(MODELFILE_TEMPLATE.format(name=target.name), encoding="utf-8")

    data = meta.get("data") or {}
    (target / "README.md").write_text(
        README_TEMPLATE.format(
            name=target.name,
            slug=slug,
            teacher=_teacher_of(meta.get("dataset", "")),
            student=student,
            run_id=run["run_id"],
            dataset=meta.get("dataset", "?"),
            pairs=data.get("pairs", "?"),
            trainable=meta.get("trainable_params", 0),
            trainable_pct=round(
                100 * meta.get("trainable_params", 0) / max(1, meta.get("total_params", 1) or 1), 3
            ),
            steps=meta.get("steps_completed", "?"),
            first_loss=meta.get("first_loss", "?"),
            final_loss=meta.get("final_loss", "?"),
            eval_loss=meta.get("best_eval_loss") or "not evaluated",
            export_dir=str(target),
            merged_dir=str(merged_dir),
            adapter_dir=str(adapter_dst),
        ),
        encoding="utf-8",
    )

    result = {
        "name": target.name,
        "path": str(target),
        "run_id": run["run_id"],
        "student": student,
        "merged": merge,
        "merged_path": str(merged_dir) if merge else None,
        "adapter_path": str(adapter_dst),
        "modelfile": str(target / "Modelfile"),
        "readme": str(target / "README.md"),
        "size_bytes": _dir_size(target),
        "ollama_command": f'cd "{target}" && ollama create {slug} -f Modelfile',
        "gguf_command": (
            f'python llama.cpp/convert_hf_to_gguf.py "{merged_dir}" '
            f'--outfile "{slug}-f16.gguf" --outtype f16'
        ),
    }
    (target / "export.json").write_text(json.dumps(result, indent=2), encoding="utf-8")
    bus.publish("export.done", **result)
    return result


def _teacher_of(dataset_name: str) -> str:
    if not dataset_name:
        return "?"
    try:
        summary = store.summarise(dataset_name)
    except FileNotFoundError:
        return "?"
    teachers = summary.get("teachers") or []
    return ", ".join(teachers) if teachers else "?"


def _merge(student: str, adapter: Path, destination: Path) -> Path:
    """Reload the base unquantised, apply the adapter, fold it in, write fp16."""
    from peft import PeftModel

    if destination.exists():
        shutil.rmtree(destination)

    kwargs: dict[str, Any] = {
        "trust_remote_code": False,
        "device_map": {"": "cpu"},
        distill._DTYPE_KWARG: torch.float16,
    }
    base = AutoModelForCausalLM.from_pretrained(student, **kwargs)
    model = PeftModel.from_pretrained(base, str(adapter), is_trainable=False)
    model = model.merge_and_unload()
    model = model.to(torch.float16)
    model.save_pretrained(str(destination), safe_serialization=True)

    tokenizer = AutoTokenizer.from_pretrained(str(adapter) if (adapter / "tokenizer_config.json").exists() else student)
    tokenizer.save_pretrained(str(destination))

    del model, base
    return destination


def sample_generate(model_dir: str | Path, prompt: str, max_new_tokens: int = 120) -> str:
    """Load an exported model and generate once. Used to prove the merge is coherent."""
    path = str(model_dir)
    tokenizer = AutoTokenizer.from_pretrained(path)
    on_gpu = torch.cuda.is_available() and config.detect_hardware()["arch_supported"]
    kwargs: dict[str, Any] = {
        "trust_remote_code": False,
        distill._DTYPE_KWARG: torch.float16 if on_gpu else torch.float32,
        "device_map": {"": 0} if on_gpu else {"": "cpu"},
    }
    model = AutoModelForCausalLM.from_pretrained(path, **kwargs)
    model.eval()

    text = distill.render_prompt(tokenizer, prompt)
    ids = tokenizer(text, add_special_tokens=False, return_tensors="pt").to(model.device)
    with torch.no_grad():
        out = model.generate(
            **ids,
            max_new_tokens=max_new_tokens,
            do_sample=True,
            temperature=0.7,
            top_p=0.9,
            pad_token_id=tokenizer.pad_token_id or tokenizer.eos_token_id,
        )
    completion = tokenizer.decode(out[0][ids["input_ids"].shape[-1] :], skip_special_tokens=True)

    del model
    if on_gpu:
        torch.cuda.empty_cache()
    return completion.strip()
